### ISSUE TITLE
Failed to invoke `workflow.onComplete` event handler

### ISSUE THREAD

**Issue by PyGuan** [nf-core/cutandrun#154]
### Description of the bug

Sep-01 22:45:20.645 [main] DEBUG nextflow.Session - Session await > all process finished
Sep-01 22:45:20.649 [main] DEBUG nextflow.Session - Session await > all barriers passed
Sep-01 22:45:20.687 [main] ERROR nextflow.script.WorkflowMetadata - Failed to invoke `workflow.onComplete` event handler
groovy.lang.GroovyRuntimeException: Failed to parse template script (your template may contain an error or be trying to use expressions not currently supported): startup failed:
GStringTemplateScript2.groovy: 82: Unexpected character: '"' @ line 82, column 48.
   ut << summary.collect{ k,v -> "
                                 ^

1 error

        at groovy.text.GStringTemplateEngine$GStringTemplate.<init>(GStringTemplateEngine.java:200)
        at groovy.text.GStringTemplateEngine.createTemplate(GStringTemplateEngine.java:114)
        at groovy.text.TemplateEngine.createTemplate(TemplateEngine.java:58)
        at groovy.text.TemplateEngine$createTemplate.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at NfcoreTemplate.email(NfcoreTemplate.groovy:108)
        at NfcoreTemplate$email$4.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at Script_225ca5b5$_runScript_closure3.doCall(Script_225ca5b5:967)
        at Script_225ca5b5$_runScript_closure3.doCall(Script_225ca5b5)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at nextflow.script.WorkflowMetadata$_invokeOnComplete_closure4.doCall(WorkflowMetadata.groovy:389)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384)
        at nextflow.script.WorkflowMetadata.invokeOnComplete(WorkflowMetadata.groovy:387)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
        at nextflow.script.WorkflowMetadata$_closure3.doCall(WorkflowMetadata.groovy:252)
        at nextflow.script.WorkflowMetadata$_closure3.call(WorkflowMetadata.groovy)
        at nextflow.Session.shutdown0(Session.groovy:675)
        at nextflow.Session.destroy(Session.groovy:625)
        at nextflow.script.ScriptRunner.terminate(ScriptRunner.groovy:222)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:122)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:337)
        at nextflow.cli.Launcher.run(Launcher.groovy:480)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)
Sep-01 22:45:21.485 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=128; failedCount=0; ignoredCount=0; cachedCount=0; pendingCoun
t=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=18h 17m 57s; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=11; pea
kCpus=96; peakMemory=384 GB; ]
Sep-01 22:45:21.485 [main] DEBUG nextflow.trace.TraceFileObserver - Flow completing -- flushing trace file
Sep-01 22:45:21.487 [main] DEBUG nextflow.trace.ReportObserver - Flow completing -- rendering html report
Sep-01 22:45:21.614 [main] DEBUG nextflow.trace.ReportObserver - Execution report summary data:

### Command used and terminal output

```console
nextflow run nf-core-cutandrun-2.0/workflow/ --input ABC.csv --igenomes_base ~/references/ --genome hg38 -profile singularity --outdir outputDir/
```

**Comment by PyGuan** [comment]
The issue appeared to be caused by "nf-core-cutandrun-2.0/workflow/assets/email_template.html".
After combining all the html tags into one single line, and the html double quotes to single quote, the issue is resolved.

**Comment by chris-cheshire** [comment]
hi yes this is fixed in the dev branch
