### ISSUE TITLE
Errors with deeptools computeMatrix

### ISSUE THREAD

**Issue by xxiann** [nf-core/cutandrun#220]
### Description of the bug

Hi, I've tried running `nextflow run nf-core/cutandrun -profile test,singularity` using nextflow 23.10.0 build 5889 and singularity-ce v4.0.2, but have been encountering exit status 1 when it reaches deeptools compute matrix process. Please do advise, tyvm!
### Command used and terminal output

```console
$ nextflow run nf-core/cutandrun -profile test,singularity

Execution cancelled -- Finishing pending tasks before exit
-[nf-core/cutandrun] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_COMPUTEMATRIX_GENE_ALL (all_genes)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_COMPUTEMATRIX_GENE_ALL (all_genes)` terminated with an error exit status (1)

Command executed:

  computeMatrix \
      scale-regions --beforeRegionStartLength 3000 --regionBodyLength 5000 --afterRegionStartLength 3000 --skipZeros --missingDataAsZero \
      --regionsFileName hg38-chr20-genes.bed \
      --scoreFileName h3k27me3_R1.bigWig \
      --outFileName all_genes.computeMatrix.mat.gz \
      --outFileNameMatrix all_genes.computeMatrix.vals.mat.tab \
      --numberOfProcessors 2

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_COMPUTEMATRIX_GENE_ALL":
      deeptools: $(computeMatrix --version | sed -e "s/computeMatrix //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Traceback (most recent call last):
    File "/usr/local/bin/computeMatrix", line 14, in <module>
      main(args)
    File "/usr/local/lib/python3.8/site-packages/deeptools/computeMatrix.py", line 421, in mai
      hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
    File "/usr/local/lib/python3.8/site-packages/deeptools/heatmapper.py", line 252, in computeMatrix
      res, labels = mapReduce.mapReduce([score_file_list, parameters],
    File "/usr/local/lib/python3.8/site-packages/deeptools/mapReduce.py", line 141, in mapReduce
      pool = multiprocessing.Pool(numberOfProcessors)
    File "/usr/local/lib/python3.8/multiprocessing/context.py", line 119, in Pool
      return Pool(processes, initializer, initargs, maxtasksperchild,
    File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 191, in __init__
      self._setup_queues()
    File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 343, in _setup_queues
      self._inqueue = self._ctx.SimpleQueue()
    File "/usr/local/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
      return SimpleQueue(ctx=self.get_context())
    File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
      self._rlock = ctx.Lock()
    File "/usr/local/lib/python3.8/multiprocessing/context.py", line 68, in Lock
      return Lock(ctx=self.get_context())
    File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
      SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
    File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
      sl = self._semlock = _multiprocessing.SemLock(
  FileNotFoundError: [Errno 2] No such file or directory

Work dir:
  /home/xiaoxian/work/de/5f7d660960843522c21f7d652dfbef

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

### Relevant files

[nextflow.log](https://github.com/nf-core/cutandrun/files/13520125/nextflow.log)

### System information

Nextflow 23.10.0
Singularity-ce v4.0.2
Ubuntu 22.04.2 LTS
nf-core/cutandrun 3.2.1

**Comment by chris-cheshire** [comment]
Is this error reproducable? I have never seen this
