### ISSUE TITLE
 Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_QC:DEEPTOOLS_MULTIBAMSUMMARY (all_target_bams)':  AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'

### ISSUE THREAD

**Issue by haipinghao** [nf-core/cutandrun#251]
### Description of the bug

I ran "nextflow run nf-core/cutandrun -profile test,conda" command after installing conda and nextflow following the instruction and got the error message

### Command used and terminal output

```console
$ nextflow run nf-core/cutandrun -profile test,conda
-[nf-core/cutandrun] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_QC:DEEPTOOLS_MULTIBAMSUMMARY (all_target_bams)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_QC:DEEPTOOLS_MULTIBAMSUMMARY (all_target_bams)` terminated with an error exit status (1)


Command executed:

  multiBamSummary bins \
      --smartLabels --binSize 500 \
      --labels h3k27me3_R1 igg_ctrl_R1 \
      --bamfiles h3k27me3_R1.target.linear_dedup.sorted.bam igg_ctrl_R1.target.linear_dedup.sorted.bam \
      --numberOfProcessors 2 \
      --outFileName all_bam.bamSummary.npz

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_QC:DEEPTOOLS_MULTIBAMSUMMARY":
      deeptools: $(multiBamSummary --version | sed -e "s/multiBamSummary //g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/NGS_Core/CutAndRun/work/conda/env-0d01150023c68e439ebff3eb959d98bf/bin/multiBamSummary", line 5, in <module>
      from deeptools.multiBamSummary import main
    File "/NGS_Core/CutAndRun/work/conda/env-0d01150023c68e439ebff3eb959d98bf/lib/python3.11/site-packages/deeptools/multiBamSummary.py", line 9, in <module>
      import deeptools.countReadsPerBin as countR
    File "/NGS_Core/CutAndRun/work/conda/env-0d01150023c68e439ebff3eb959d98bf/lib/python3.11/site-packages/deeptools/countReadsPerBin.py", line 9, in <module>
      import deeptools.utilities
    File "/NGS_Core/CutAndRun/work/conda/env-0d01150023c68e439ebff3eb959d98bf/lib/python3.11/site-packages/deeptools/utilities.py", line 7, in <module>
      from deeptools import cm  # noqa: F401
      ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/NGS_Core/CutAndRun/work/conda/env-0d01150023c68e439ebff3eb959d98bf/lib/python3.11/site-packages/deeptools/cm.py", line 1087, in <module>
      mpl_cm.register_cmap(_name, _cmap)
      ^^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'

Work dir:
  /NGS_Core/CutAndRun/work/df/50bbc2679a218fcccf7c49502a3ac4

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

### System information

Nextflow version 24.04.4
Hardware: multicore server
Executor: none
Container engine: Conda
OS: Ubuntu
Version of  nf-core/cutandrun v3.2.2-g6e1125d

**Comment by chris-cheshire** [comment]
Looks like a cluster issue, is this still a problem?

**Comment by haipinghao** [comment]
Thank you for your response.  No, this is no longer an issue.

**Comment by kdorman** [comment]
I also encountered this error when using container conda. Fixed by adding `matplotlib=3.5` to conda line of `main.nf` in `modules/nf-core/deeptools/multibamsummary` and other deeptools modules in the `cutandrun` pipeline, but probably there is a better fix (next paragraph) that I did not test.

Matplotlib deprecated `register_cmap` in version 3.6 and removed it in 3.7. Perhaps the error was caused because I accidentally had bioconda channel before conda-forge channel in conda configuration, itself a warning message at the top of the nextflow log, but easy to miss. If this was the issue, then you may wish to update documentation in [Getting Started->Dependency Installation](https://nf-co.re/docs/usage/getting_started/installation) to say `conda config --add channels` commands order is important. [Bioconda](https://bioconda.github.io/#explain-commands) also recommends using `conda config --set channel_priority strict` after adding the channels. If channel order was the issue, then I recommend you turn that warning into an error message. It is much easier to fix the warning than to debug the actual error message.

**System Information**
container conda
nextflow version 24.10.4.5934
nf-core/cutandrun v3.2.2
