### ISSUE TITLE
NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_PEAKS terminated with an error exit status (137)

### ISSUE THREAD

**Issue by monovich** [nf-core/cutandrun#254]
### Description of the bug

I'm getting an issue with a single file on the DEEPTOOLS_PLOTHEATMAP_PEAKS step of the pipeline (out of 140). I'm trying to resume the pipeline but it keeps hanging on this step for this file. Any advice on how to debug this? I'm trying to avoid rerunning the whole pipeline over a single file error.

### Command used and terminal output

```console
nextflow run nf-core/cutandrun \
--input ${SAMPLESHEET} \
--peakcaller 'seacr,MACS2' \
--fasta $FASTA \
--gtf $GTF \
--blacklist $BLACKLIST \
--outdir $OUTDIR \
--normalization_mode "CPM" \
--remove_mitochondrial_reads \
--mito_name "chrM" \
--dedup_target_reads \
-work-dir $WORKDIR \
-r 3.2.2

ERROR ~ Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_PEAKS (BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_PEAKS (BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1)` terminated with an error exit status (137)


Command executed:

  plotHeatmap \
      --sortUsing sum --startLabel "Peak Start" --endLabel "Peak End" --xAxisLabel "" --regionsLabel "Peaks" \
      --matrixFile BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1.computeMatrix.mat.gz \
      --outFileName BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1.plotHeatmap.pdf \
      --outFileNameMatrix BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1.plotHeatmap.mat.tab

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_PEAKS":
      deeptools: $(plotHeatmap --version | sed -e "s/plotHeatmap //g")
  END_VERSIONS

Command exit status:
  137

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /opt/singularity/4.1.3/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-mx3ftuav because the default path (/home/monovich/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  .command.sh: line 6:    45 Killed                  plotHeatmap --sortUsing sum --startLabel "Peak Start" --endLabel "Peak End" --xAxisLabel "" --regionsLabel "Peaks" --matrixFile BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1.computeMatrix.mat.gz --outFileName BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1.plotHeatmap.pdf --outFileNameMatrix BALL_PRIM_PED_BCRABL1_044_PSR25_CUTRUN_H3K27me3_CST9733S_native_R1.plotHeatmap.mat.tab
```

### Relevant files

[nextflow.log](https://github.com/user-attachments/files/16677649/nextflow.log)

### System information

Nextflow 24.04.1
Hardware HPC
Executor Slurm
Container Singularity
OS CentOS Linux
nf-core/cutandrun v3.2.2.-g6e1125d

**Comment by chris-cheshire** [comment]
Hi, this is not a bug persay, this is an out of memory error. Is your sample quite large? if yes then you may need to add more memory to the process with a custom config

**Comment by schweineimweltall** [comment]
Hi, I'm running the cutandrun pipeline version 3.2.2 (Nextflow 24.04.4) on my samples using 

`$ nextflow run nf-core/cutandrun --input samplesheet.csv  --outdir /home/herbst/Documents/nextflow_EC_h3k4me3_h3k27ac --genome GRCh38 -profile docker`

and get the same error message (as described above):

```
Caused by:
  "Process `NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_PEAKS (H3K27ac_R1)` terminated with an error exit status (137)"

Command executed:
  plotHeatmap \
      --sortUsing sum --startLabel "Peak Start" --endLabel "Peak End" --xAxisLabel "" --regionsLabel "Peaks" \
      --matrixFile H3K27ac_R1.computeMatrix.mat.gz \
      --outFileName H3K27ac_R1.plotHeatmap.pdf \
      --outFileNameMatrix H3K27ac_R1.plotHeatmap.mat.tab

Command error:
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-qguj_kbw because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, ...
```

It looks like as if my HPC with 100 GB of RAM is running out of memory and writing data to a temporary file is failing due to missing writing rights ("default path (/.config/matplotlib) is not a writable directory").

To solve the problem, I have two questions:
1) How and where do I set the MPLCONFIGDIR environment variable? 
	- I tried using the command "export MPLCONFIGDIR="~/tmp/mplconfigdir" in bash. But that didn't work out.

2) How do I "add more memory to the process with a custom config" as suggested by chris-cheshire?

Kind regards,
Andreas

**System information**
Nextflow 24.04.4
Hardware HPC with 100 GB RAM
Container Docker
OS SLES 15.5
nf-core/cutandrun v3.2.2.-6e1125d4fe

**Comment by aakashsur** [comment]
Running into the same issue!

**Comment by johnvusich** [comment]
Hi, I am running into a similar issue with 32 samples. I tried adding more memory to the failed processes using the custom config below, but it still failed.

### Command used and terminal output
```bash
# Run the CUT&RUN analysis
nextflow run nf-core/cutandrun -r 3.2.2 -profile singularity -resume \
    --input $OUTPUT_DIR/samplesheet.csv \
    --outdir $OUTPUT_DIR/results \
    --fasta $FASTA_FILE \
    --gtf $GTF_FILE \
    --read_length 75 \
    --blacklist $OUTPUT_DIR/hg38-blacklist.v2.bed.txt \
    -w $WORK_DIR \
    -c $OUTPUT_DIR/icer.config

Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_GENE_ALL (all_genes)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_GENE_ALL (all_genes)` terminated with an error exit status (137)


Command executed:

  plotHeatmap \
      --sortUsing sum \
      --matrixFile all_genes.computeMatrix.mat.gz \
      --outFileName all_genes.plotHeatmap.pdf \
      --outFileNameMatrix all_genes.plotHeatmap.mat.tab
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_GENE_ALL":
      deeptools: $(plotHeatmap --version | sed -e "s/plotHeatmap //g")
  END_VERSIONS

Command exit status:
  137

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /var/lib/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  .command.sh: line 6:    43 Killed                  plotHeatmap --sortUsing sum --matrixFile all_genes.computeMatrix.mat.gz --outFileName all_genes.plotHeatmap.pdf --outFileNameMatrix all_genes.plotHeatmap.mat.tab
```
### Custom config
```
process {
    executor = 'slurm'
    
    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:FRAG_LEN_HIST' {
        time = '12h'
        memory = '72 GB'
        cpus = 16
    }
    
    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_GENE_ALL' {
        time = '12h'
        memory = '48 GB'
        cpus = 16
    }
}
```
### Relevant files
[r5020_cutandrun-51038564.log](https://github.com/user-attachments/files/18932954/r5020_cutandrun-51038564.log)

### System Information
Nextflow 24.10.2
Hardware HPC
Executor Slurm
Container Singularity
OS Ubuntu 22.04.5 LTS
nf-core/cutandrun v3.2.2

**Comment by johnvusich** [comment]
Update: I was able to get the pipeline to run successfully with this custom config:

```
process {
    executor = 'slurm'
    withName: 'NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_GENE_ALL' {
        memory = 72.GB
        cpus = 8
        errorStrategy = { task.exitStatus == 137 ? 'retry' : 'terminate' }
        maxRetries = 3
        maxMemory = 128.GB
    }
}
```

**Comment by Matthew-Dyer792** [comment]
I have encountered the same issue as above

```
nextflow-24.10.4-dist run "${PIPELINE_DIR}" \
-profile singularity \
--input "${WORKING_DIR}/samplesheet.csv" \
--outdir "${WORKING_DIR}/results" \
--peakcaller 'SEACR,MACS2' \
--fasta "${FASTA}" \
--gtf "${GTF}" \
--bowtie2 "${BOWTIE2_INDEX}" \
--blacklist "${BLACK_LIST}" \
--use_control 'false' \
--mito_name 'MT' \
--macs_gsize 2913022398 \
--save_reference \
-resume

Process `NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_GENE (V_D9_M3_C_R1)` terminated with an error exit status (137)

Command executed:

#!/bin/bash -euo pipefail
plotHeatmap \
    --sortUsing sum \
    --matrixFile V_D9_M3_C_R1.computeMatrix.mat.gz \
    --outFileName V_D9_M3_C_R1.plotHeatmap.pdf \
    --outFileNameMatrix V_D9_M3_C_R1.plotHeatmap.mat.tab

cat <<-END_VERSIONS > versions.yml
"NFCORE_CUTANDRUN:CUTANDRUN:DEEPTOOLS_PLOTHEATMAP_GENE":
    deeptools: $(plotHeatmap --version | sed -e "s/plotHeatmap //g")
END_VERSIONS

Command error:
  WARNING: Skipping mount /mnt/beegfs02/software/recherche/singularity-ce/4.2.2/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Matplotlib created a temporary config/cache directory at /mnt/beegfs02/scratch/m_dyer/tmp/matplotlib-sm2kku87 because the default path (/home/m_dyer/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  /mnt/beegfs02/scratch/m_dyer/Novogene_H204SC25053862/analysis/cutntag-20250624/nfcore/work/bb/f9beb9b8d09a3745b3f3af8651636a/.command.sh: line 6:    43 Killed                  plotHeatmap --sortUsing sum --matrixFile V_D9_M3_C_R1.computeMatrix.mat.gz --outFileName V_D9_M3_C_R1.plotHeatmap.pdf --outFileNameMatrix V_D9_M3_C_R1.plotHeatmap.mat.tab
```

When I went to recreate the error with conda, I got:

```
Traceback (most recent call last):
  File "/home/m_dyer/Conda_envs/deeptools/bin/plotHeatmap", line 5, in <module>
    from deeptools.plotHeatmap import main
  File "/home/m_dyer/Conda_envs/deeptools/lib/python3.11/site-packages/deeptools/plotHeatmap.py", line 22, in <module>
    from deeptools import cm  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m_dyer/Conda_envs/deeptools/lib/python3.11/site-packages/deeptools/cm.py", line 1087, in <module>
    mpl_cm.register_cmap(_name, _cmap)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'
```

It looks like the conda and singularity for deeptools version 3.5.1 use a deprecated call within matplotlib. After changing the version used by the pipeline, the error was resolved.

Before:

```
    conda "bioconda::deeptools=3.5.1"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/deeptools:3.5.1--py_0' :
        'biocontainers/deeptools:3.5.1--py_0' }"
```

After:

```
    conda "bioconda::deeptools=3.5.5"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/deeptools:3.5.5--pyhdfd78af_0':
        'biocontainers/deeptools:3.5.5--pyhdfd78af_0' }"
```
